### ISSUE TITLE
Language field in the pages SQL table is too short

### ISSUE THREAD

**Issue by mebeim** [principis/tldr-sharp#1]
I was looking at the code in `Program.cs` and I see you're using a `VARCHAR(2)` for the language when creating the `pages` table ([here](https://github.com/principis/tldr-sharp/blob/master/tldr-sharp/Program.cs#L409)). Language identifiers can be longer than 2 characters, as described [here in the translation guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#translations) (I'd say they could reach up to 7 characters), so this should probably be updated.

**Comment by principis** [comment]
Hi, thanks for letting me know. I was in the process of updating to follow the [spec](https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md) but I haven't got time to finish it. I'll probably fix it in the following week. :)

**Comment by principis** [comment]
Fixed in 7086db31fa750d734e86a208ce3e07bfcca22858

**Comment by mebeim** [comment]
@principis great! :)
