### ISSUE TITLE
incorrect display in cmd, windows powershell 

### ISSUE THREAD

**Issue by zhangzp9970** [principis/tldr-sharp#2]
the color doesn't display correctly in windows cmd, powershell. 
However, it works in the new windows terminal
![图片](https://user-images.githubusercontent.com/56378403/68066469-94bd2180-fd73-11e9-9a21-592cfef1fc02.png)
![图片](https://user-images.githubusercontent.com/56378403/68066476-a6062e00-fd73-11e9-9811-ca2034c5059a.png)

**Comment by principis** [comment]
Which version of windows are you using? CMD and powershell prior to windows 10 1511 do not support ANSI and VT100 escape sequences [source](https://stackoverflow.com/a/35864976). Maybe you find a solution over there.

I may be able to disable it for those versions so it doesn't look broken.

**Comment by zhangzp9970** [comment]
I use the latest windows version 10.0.18362.449

**Comment by principis** [comment]
@zhangzp9970 sorry for the late response, I'm currently really busy.
I'll look into disabling it if the shell doesn't support it, if possible. Otherwise it'll be a won't fix. :/

**Comment by zhangzp9970** [comment]
never mind, I think it is just Windows's fault.

**Comment by principis** [comment]
@zhangzp9970 I've prepared release [2.3.3-beta](https://github.com/principis/tldr-sharp/releases/tag/v2.3.3-beta). It should be fixed now. Let me know if any issues arise!

**Comment by principis** [comment]
Release 2.3.3 seems to work fine on windows.
