### ISSUE TITLE
BadImageFormatException in Mono.Data.Sqlite with Releases starting from v2.6.1

### ISSUE THREAD

**Issue by romibi** [principis/tldr-sharp#5]
Using any Release newer than v2.6.0 (I tried each release from v2.6.1 to v2.6.4) results in the following exception for me:

```
Unbehandelte Ausnahme: System.BadImageFormatException: Es wurde versucht, eine Datei mit einem falschen Format zu laden. (Ausnahme von HRESULT: 0x8007000B)
   bei Mono.Data.Sqlite.UnsafeNativeMethods.sqlite3_open_v2(Byte[] utf8Filename, IntPtr& db, Int32 flags, IntPtr vfs)
   bei Mono.Data.Sqlite.SQLite3.Open(String strFilename, SQLiteOpenFlagsEnum flags, Int32 maxPoolSize, Boolean usePool)
   bei Mono.Data.Sqlite.SqliteConnection.Open()
   bei tldr_sharp.Index.ListLanguages()
   bei tldr_sharp.Locale.GetPreferredLanguages()
   bei tldr_sharp.PageController.Print(String pageName, String prefLanguage, String platform, Boolean markdown)
   bei tldr_sharp.Program.doMain(String[] args)
   bei tldr_sharp.Program.Main(String[] args)
```

The first line translated means something like
`Unhandled Exception: System.BadImageFormatException: It was attempted to load a file with a wrong format.`
`bei` means `at`

I also tried clearing cache with v2.6.4 which did not help.
I also tried to replace the .tldr folder with a copy from v2.6.0 while v2.6.4 is installed … did not help as well …
Release v2.6.0 works.

**Comment by principis** [comment]
Thanks for the report! What is your OS?

**Comment by romibi** [comment]
I'm using Windows 11 (x64 of course)
Version 22H2 (Build 22621.1848)

I installed tldr-sharp using the setup.

The exception happens wenn e.g. calling `tldr git`.

It happens when calling it from Windows-Terminal Version: 1.17.11461.0
Using the default "Eingabeaufforderung" (Command Prompt, cmd) Profile
As well as when using conhost (the old cmd host instead of the windows terminal)

**Comment by principis** [comment]
I currently don't have access to a Windows 11 machine until tonight. 

If you have some time, please try the following things: 

- Update the sqlite3 library:  Download the [latest release](https://www.sqlite.org/2023/sqlite-dll-win64-x64-3420000.zip) and replace sqlite3.dll in the tldr-sharp install directory.
- If that doesn't work, try this rebuild using net48: [net48.zip](https://github.com/principis/tldr-sharp/files/11770697/net48.zip)

**Comment by romibi** [comment]
Yes, installing v2.4.6 and then replacing the sqlite3.dll with the linked one does get me a working tldr-sharp 2.4.6
Yes, downloading the zip, extracting it and calling `tldr-sharp.exe git` from inside it works as well …

**Comment by principis** [comment]
Thanks for testing! The problem seems to be that the installed dll is for x86. I'm not sure why this is only happening now.

You can safely use 2.6.4 and replace the dll. I need to do some further testing before releasing a fix.
